line_length:
  warning: 130
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true

disabled_rules:
  - large_tuple
  - identifier_name
  - unused_optional_binding
  - switch_case_alignment

excluded:
  - Carthage
  - Pods

